#!/bin/bash

while getopts ":hft" opt; do 
    case ${opt} in
      h )
        echo "Usage:"
        echo "    scplxplus [-f] [-t] source dest"
        exit 0
        ;;
      f )
        shift
        last=${@:$#}
        other=${*%${!#}}
        # sshpass -f ~/.lxplus.pass scp -r -4 kiliakis@lxplus8.cern.ch:"$other" $last
        sshpass -f ~/.lxplus.pass rsync -rv --progress kiliakis@lxplus8.cern.ch:"$other" $last
        ;;
      t )
        shift
        last=${@:$#}
        other=${*%${!#}}
        # sshpass -f ~/.lxplus.pass scp -r -4 $other kiliakis@lxplus8.cern.ch:$last
        sshpass -f ~/.lxplus.pass rsync -rv --progress $other kiliakis@lxplus8.cern.ch:$last
        ;;
      \? ) echo "Usage scplxplus [-f] [-t] source dest"
        ;;
     esac
done
